# Generated by Django 5.0.6 on 2024-06-13 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='ful_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='startcourse',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(help_text='Bir oylik kurs narxi'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.startcourse')),
            ],
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='lesson/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'WMV'])])),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lesson')),
            ],
        ),
    ]
