# Generated by Django 5.0.6 on 2024-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_camment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camment',
        ),
    ]
