# Generated by Django 5.0.6 on 2024-06-13 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_camment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camment',
            name='lesson',
        ),
        migrations.AddField(
            model_name='camment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.lesson'),
            preserve_default=False,
        ),
    ]
