# Generated by Django 5.0.6 on 2024-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_camment_lesson_camment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startcourse',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
