# Generated by Django 5.0.6 on 2024-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_startcourse_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/img/'),
        ),
    ]
